apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: staging
spec:
  encryptedData:
    .dockerconfigjson: AgBMCUHraZttJwqzmLIv8e13vi5cqa2Rz9xF4Az44DO7vVxilLwG2QFGHSJ7YuV/KYvOjSvHSvSOFfStW3zwHxwoJhYzgW659JjKfAId2ENsw0HfoE0+UYl63lp7crOfOvyKgX3fHly+ZOxR3AnY+fj7joy2Sh1UN1ySJQnzfMwgbE0+5ZkPvQfRrS65+s7hW1vNwKNnErOo28y7ZNRmI3g0T7jwQi7ntDhnQpKiyKnVNZQZ/ociZuiOQPuxFxJXGiZ4H6HHaOsP7oBxjOOKvyK7fbL8zDYHkckxxCu1va+o531t9Z72PbXDQw96aargnJBP0vd59SXmgKBHn8OynLOWjJO0DRNdn0XQ+HvAAC3C/6D4lxrdFi572qk0CyYvGPrIxL9P9Cw9ZEWIirmAyMA+eag38MWQd464KaLuyoy92/2tkJhvxb3PHnNtmsbqCyLDUwfkIUoosi5PhePhTdjpTi2nssGdzk5+EROkh3Q0DyrULbllTUKXz65DFWwXuCa2gczZHYqi8tOchfS2YdWpoT8amRJdBwYh4RUZ9bwFX13ukNsyVg6r2VeF9UHk+MGkomZ60a7wBlXiigICZWl2s71CrvFHF6R3H7zLXLJH70N++m69sNjRpzdCZTc2qrp0XhBcZuvIzZWlENKtVTrN4wX5o96JsUxcC0SRDzARarU7Yjc1wBZ8gtf3EsJSCku6dGVxxa7vm4GQq3HxbAeomT+qzKKgxI8WGcbxSits6Puav2AhOVkH0jKoEOEEfIFHOGECAQiYp2vdo1E4AQIe2NlONRcfvHehUyDpzJoVKuCgy7wReF9DntSPhrRNo6GVJyQdBrfjVvRRJc1ZZZnKxRDLUNPqPpt8Lh12cCyBkvcYdTDeRkJcHjSOaArLATWEJvNxFj1GWxQR5Pcu6AG2qscJHMg9LhFWE5iDbJ6bgAyyOXIHdYDnBEj4LHyS2Fw9JbwoDuI0w1NW2ID1AtZVIcIlBZmKDTvYFRCh74M=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: staging
    type: kubernetes.io/dockerconfigjson

