apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-combined-app
spec:
  rules:
  - host: argo-combined-app.pilifo.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
           name: argo-combined-app
           port:
             number: 80
